### ISSUE TITLE
constellation: uploading files depending on each other

### ISSUE THREAD

**Issue by Flemmli97** [Satellite-im/Warp#435]
When trying to upload multiple files via `warp::constellation::Constellation::put` (via e.g. a loop)
the returning `ConstellationProgressStream` only ends when all of the files are finished with uploading.

Expected behaviour would be instead that each stream will end when their respective progress is done.

```rs
for file in files {
     match warp_storage.put(&file, &some_path).await {
            Ok(upload_progress) => {
                // Handle each upload on another thread
                let mut warp_storage = warp_storage.clone();
                let res = tx.clone();
                tokio::spawn(async move {
                   // handle upload_progress
                   // upload_progress only ends if all files are done uploading
                   future_foo(upload_progress).await;
                });
            }
            Err(error) => log::error!("Error when upload file: {:?}", error),
        }
}
```

**Comment by dariusc93** [comment]
Just as a note:

This is mostly intentional to make sure that the index can be exported without repeated hits if the index itself is updated in any way. While I do see how this can be confusing when polling individual streams and moving notified waiter to after yielding the complete event from stream *should* correct it, I can imagine this being problematic if the stream is dropped right away after the event. If I do make the change though, it would be best to make sure that the stream itself completes on it own (eg that it returns `None`, though if youre polling using a `while let Some(some_item) = stream.next().await` then this would drop on its own once the stream is done).
