### ISSUE TITLE
bug: Problem on UplinkWeb when we use tesseract.load_from_storage function

### ISSUE THREAD

**Issue by lgmarchi** [Satellite-im/Warp#518]
##### a. Problem that happens when I use create_identity.
<img width="490" alt="image" src="https://github.com/Satellite-im/Warp/assets/63157656/a1d2fd1f-5c37-4263-b45e-897b9280d315">

##### b. Local Storage
<img width="686" alt="image" src="https://github.com/Satellite-im/Warp/assets/63157656/568000bb-e142-480e-84ca-cea059fdae25">

##### b. Local Storage
<img width="674" alt="image" src="https://github.com/Satellite-im/Warp/assets/63157656/7e1f0ce0-d398-4a0e-9358-30d9f4c3a284">

**Comment by dariusc93** [comment]
This sounds like a issue or conflict in the current session since private/incognito mode would give you a new session. My advice would be to try clearing the cache and data from `localhost:5173`. I would also ask that you try to reproduce it in the rust variant of wasm (see https://github.com/Satellite-im/Warp/tree/main/extensions/warp-ipfs/examples/wasm-ipfs-identity)
